### ISSUE TITLE
RSA Error

### ISSUE THREAD

**Issue by TMQrX** [TheMajestry/golang-crypter#1]
I have some trouble when trying to build the encryption file.
![image](https://github.com/TheMajestry/golang-crypter/assets/86949469/a610654b-0192-4c09-a7e0-2727e0ffd08d)

**Comment by TMQrX** [comment]
The rat I used is AsyncRat

**Comment by TheMajestry** [comment]
Ahh I see well,

**Comment by TheMajestry** [comment]
Ahh I see well, this crypter is 3-4years ago.
This error will appear when you use a obf function of AsyncRAT
